#!/usr/bin/env python3
"""Original generator for pipeline_comparison.ipynb.

**Do not run this.** It writes pipeline_comparison.ipynb unconditionally, and
the live notebook has been hand-patched well beyond what's here — running this
silently reverts all of it. Kept only as the record of how the notebook was
originally laid out.

If you need to change the notebook, edit the notebook.
"""
import json, uuid
from pathlib import Path

def cell_id():
    return uuid.uuid4().hex[:8]

def md(src):
    return {"cell_type": "markdown", "id": cell_id(), "metadata": {}, "source": src}

def code(src):
    return {
        "cell_type": "code", "id": cell_id(), "execution_count": None,
        "metadata": {}, "outputs": [], "source": src
    }

cells = []

# ── Section 1: Title ──────────────────────────────────────────────────────────
cells.append(md(
    "# Pipeline Comparison: MIMIC_Extract vs EHR-Dataset-Processing\n\n"
    "Does the published academic preprocessing pipeline give a better downstream\n"
    "classifier signal than the in-house one? Everything here is arranged to make\n"
    "that a fair question.\n\n"
    "The two pipelines are aligned on cohort (the ~27k hospital admissions both\n"
    "produce), label (hospital mortality), features (the same seven bedside vitals),\n"
    "and window (first 24 hours). Same classifier, same seeds, same splits. So the\n"
    "only thing left varying is the preprocessing itself — which is the point.\n\n"
    "Watch out for one thing when reading the results: the pipelines disagree on\n"
    "what hour 0 means. MIMIC_Extract anchors on ICU admission, EHR-Dataset-\n"
    "Processing on hospital admission. For a patient who spent time on a ward\n"
    "first, the two 24-hour windows cover different periods."
))

# ── Section 2: Imports ────────────────────────────────────────────────────────
cells.append(md("## Setup & Imports"))
cells.append(code(
    "import warnings\n"
    "import pickle\n"
    "import functools\n"
    "from pathlib import Path\n"
    "from typing import List, Tuple\n"
    "\n"
    "from IPython.display import display\n"
    "\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import matplotlib.colors as mcolors\n"
    "import matplotlib.pyplot as plt\n"
    "import matplotlib.ticker as mticker\n"
    "from mpl_toolkits.mplot3d import Axes3D\n"
    "from scipy.interpolate import griddata\n"
    "from scipy.stats import binom\n"
    "\n"
    "from sklearn.linear_model import LogisticRegression\n"
    "from sklearn.model_selection import StratifiedShuffleSplit\n"
    "from sklearn.preprocessing import StandardScaler\n"
    "from sklearn.metrics import accuracy_score, f1_score, roc_auc_score\n"
    "\n"
    "from tabulate import tabulate\n"
    "\n"
    "plt.rcParams.update({\n"
    "    'figure.facecolor':  '#191a1c',\n"
    "    'axes.facecolor':    '#191a1c',\n"
    "    'axes.edgecolor':    '#ffffff',\n"
    "    'axes.labelcolor':   '#ffffff',\n"
    "    'xtick.color':       '#ffffff',\n"
    "    'ytick.color':       '#ffffff',\n"
    "    'text.color':        '#ffffff',\n"
    "    'grid.color':        '#3a3b3d',\n"
    "    'grid.linestyle':    ':',\n"
    "    'grid.linewidth':    0.5,\n"
    "    'legend.facecolor':  '#2a2b2d',\n"
    "    'legend.edgecolor':  '#ffffff',\n"
    "})"
))

# ── Section 3: Configuration ──────────────────────────────────────────────────
cells.append(md("## Configuration"))
cells.append(code(
    "MIMIC_HDF = Path('../pipelines/MIMIC_Extract/data/curated/baseline_nofilters/all_hourly_data.h5')\n"
    "EHR_PKL   = Path('../pipelines/EHR-Dataset-Processing/Data/mimic-iii/processed_record_ehr.pkl')\n"
    "\n"
    "AGG_METHODS = [\n"
    "    'mean', 'median', 'standard deviation', 'mean deviation', 'maximum deviation'\n"
    "]\n"
    "\n"
    "SEEDS      = [22, 985, 439, 81]\n"
    "TEST_SIZE  = 0.2\n"
    "MODEL_KWARGS = dict(max_iter=500, solver='liblinear', random_state=0)\n"
    "\n"
    "# The two pipelines spell this one vital differently and nothing else\n"
    "# differs, so a one-entry map is the whole reconciliation. Miss it and\n"
    "# respiration rate silently comes through as all-NaN on the EHR side.\n"
    "VITAL_NAME_MAP = {'respiration rate': 'respiratory rate'}\n"
    "\n"
    "VITAL_NAMES = [\n"
    "    'heart rate',\n"
    "    'systolic blood pressure',\n"
    "    'diastolic blood pressure',\n"
    "    'mean blood pressure',\n"
    "    'respiratory rate',\n"
    "    'temperature',\n"
    "    'oxygen saturation',\n"
    "]"
))

# ── Section 4: Aurora Viz Helpers ─────────────────────────────────────────────
cells.append(md(
    "## Aurora Visualization Helpers\n\n"
    "All plots use the Aurora dark theme (background `#191a1c`, gradient\n"
    "`#191a1c → #724ed5 → #4ED595`). Functions mirrored from\n"
    "`EHR-Dataset-Processing/Managers/visualization_manager.py`."
))
cells.append(code(
    "def generate_hex_gradient(colours: List[str], gradient_length: int) -> List[str]:\n"
    "    if len(colours) < 2:\n"
    "        raise ValueError('At least two colors required.')\n"
    "    if gradient_length == 1:\n"
    "        return [colours[0]]\n"
    "    rgb_colors = np.array([mcolors.to_rgb(c) for c in colours])\n"
    "    segments   = len(colours) - 1\n"
    "    gradient   = []\n"
    "    for i in range(gradient_length):\n"
    "        pos         = i / (gradient_length - 1)\n"
    "        seg         = min(int(pos * segments), segments - 1)\n"
    "        seg_pos     = (pos - seg / segments) * segments\n"
    "        interp      = rgb_colors[seg] + (rgb_colors[seg + 1] - rgb_colors[seg]) * seg_pos\n"
    "        gradient.append(mcolors.to_hex(interp))\n"
    "    return gradient\n"
    "\n"
    "_AURORA = ['#191a1c', '#724ed5', '#4ED595']\n"
    "_BG     = '#191a1c'\n"
    "\n"
    "def _aurora_cmap():\n"
    "    g = generate_hex_gradient(_AURORA, 20)\n"
    "    return mcolors.LinearSegmentedColormap.from_list('aurora', g, N=20)\n"
    "\n"
    "def generate_3d_plot(df: pd.DataFrame, title: str = '3D Surface',\n"
    "                     x_title: str = '', y_title: str = '', z_title: str = '',\n"
    "                     background_colour: str = _BG):\n"
    "    if not np.issubdtype(df.values.dtype, np.number):\n"
    "        raise ValueError('DataFrame must be numeric.')\n"
    "    rows, cols = df.shape\n"
    "    X, Y = np.meshgrid(np.arange(cols), np.arange(rows))\n"
    "    Z    = df.values.astype(float)\n"
    "    X_s  = np.linspace(0, cols - 1, cols * 10)\n"
    "    Y_s  = np.linspace(0, rows - 1, rows * 10)\n"
    "    Xg, Yg = np.meshgrid(X_s, Y_s)\n"
    "    Zg = griddata(np.column_stack((X.flatten(), Y.flatten())), Z.flatten(),\n"
    "                  (Xg, Yg), method='cubic')\n"
    "    cmap   = _aurora_cmap()\n"
    "    fig    = plt.figure(figsize=(12, 6), facecolor=background_colour)\n"
    "    ax     = fig.add_subplot(111, projection='3d', facecolor=background_colour)\n"
    "    surf   = ax.plot_surface(Xg, Yg, Zg, cmap=cmap, edgecolor='none')\n"
    "    ax.set_xlabel(x_title); ax.set_ylabel(y_title); ax.set_zlabel(z_title)\n"
    "    ax.set_xticks(np.arange(cols))\n"
    "    ax.set_xticklabels(df.columns, rotation=45, ha='right')\n"
    "    for pane in (ax.xaxis, ax.yaxis, ax.zaxis):\n"
    "        pane.pane.fill = False\n"
    "        pane._axinfo['grid']['color']     = '#3a3b3d'\n"
    "        pane._axinfo['grid']['linewidth'] = 0.5\n"
    "        pane._axinfo['grid']['linestyle'] = ':'\n"
    "        pane._axinfo['edgecolor']         = '#3a3b3d'\n"
    "    cbar = fig.colorbar(surf, ax=ax, shrink=0.6, pad=0.1)\n"
    "    cbar.outline.set_visible(False)\n"
    "    ax.set_title(title, color='white')\n"
    "    import warnings as _w\n"
    "    with _w.catch_warnings():\n"
    "        _w.simplefilter('ignore', UserWarning)\n"
    "        plt.tight_layout()\n"
    "    plt.show()\n"
    "\n"
    "def generate_heatmap(df: pd.DataFrame, title: str = 'Heatmap',\n"
    "                     x_title: str = '', y_title: str = '', annotate: bool = True):\n"
    "    if not np.issubdtype(df.values.dtype, np.number):\n"
    "        raise ValueError('DataFrame must be numeric.')\n"
    "    nr, nc  = df.shape\n"
    "    cmap    = _aurora_cmap()\n"
    "    fig, ax = plt.subplots(figsize=(10, 7), facecolor=_BG)\n"
    "    hm      = ax.imshow(df.values, cmap=cmap, aspect='auto', origin='lower')\n"
    "    ax.set_xticks(np.arange(nc))\n"
    "    if nc <= 50:\n"
    "        ax.set_xticklabels(df.columns, rotation=45, ha='right', color='white')\n"
    "    else:\n"
    "        step = max(1, nc // 24)\n"
    "        shown = np.arange(0, nc, step)\n"
    "        ax.set_xticks(shown)\n"
    "        ax.set_xticklabels([list(df.columns)[i] for i in shown],\n"
    "                           rotation=45, ha='right', color='white')\n"
    "    ax.set_yticks(np.arange(nr)); ax.set_yticklabels(df.index, color='white')\n"
    "    ax.set_xlabel(x_title, color='white'); ax.set_ylabel(y_title, color='white')\n"
    "    ax.set_title(title, color='white')\n"
    "    ax.set_xticks(np.arange(-0.5, nc, 1), minor=True)\n"
    "    ax.set_yticks(np.arange(-0.5, nr, 1), minor=True)\n"
    "    ax.grid(which='minor', color='#3a3b3d', linestyle=':', linewidth=0.5)\n"
    "    ax.tick_params(which='minor', bottom=False, left=False)\n"
    "    if annotate:\n"
    "        for i in range(nr):\n"
    "            for j in range(nc):\n"
    "                v = df.values[i, j]\n"
    "                if not np.isnan(v):\n"
    "                    ax.text(j, i, f'{v:.1f}', ha='center', va='center',\n"
    "                            color='white', fontsize=8)\n"
    "    for sp in ax.spines.values():\n"
    "        sp.set_visible(False)\n"
    "    ax.set_frame_on(False)\n"
    "    cbar = fig.colorbar(hm, ax=ax, shrink=0.7)\n"
    "    cbar.outline.set_visible(False)\n"
    "    import warnings as _w\n"
    "    with _w.catch_warnings():\n"
    "        _w.simplefilter('ignore', UserWarning)\n"
    "        plt.tight_layout()\n"
    "    plt.show()\n"
    "\n"
    "def visualize_pipeline_impact(scores: List[float], pipeline_names: List[str],\n"
    "                               metric: str, aggregation_method: str,\n"
    "                               epsilon: float = 1e-3, min_range: float = 0.005):\n"
    "    reference      = scores[0]\n"
    "    scores_to_plot = np.array(scores[1:])\n"
    "    deviations     = scores_to_plot - reference\n"
    "    indices        = np.arange(len(scores_to_plot))\n"
    "    bar_colors     = np.where(deviations > epsilon, '#3b8465',\n"
    "                     np.where(deviations < -epsilon, '#bd3140', '#a0a0a0'))\n"
    "    fig, ax = plt.subplots(figsize=(8, 6), facecolor=_BG)\n"
    "    ax.bar(indices, deviations, color=bar_colors, width=0.5, zorder=3)\n"
    "    for i, dev in enumerate(deviations):\n"
    "        va     = 'bottom' if dev >= 0 else 'top'\n"
    "        offset = 0.0005 if dev >= 0 else -0.0005\n"
    "        ax.text(i, dev + offset, f'{dev:+.4f}', ha='center', va=va,\n"
    "                color='#a0a0a0', fontsize=11, fontweight='bold')\n"
    "    ax.set_xticks(indices)\n"
    "    ax.set_xticklabels(pipeline_names, rotation=30, ha='right', fontsize=11)\n"
    "    dev_range = deviations.max() - deviations.min() if len(deviations) > 1 else 0.0\n"
    "    if dev_range < min_range:\n"
    "        ax.set_ylim(-min_range * 1.2, min_range * 1.2)\n"
    "    else:\n"
    "        m = dev_range * 0.3\n"
    "        ax.set_ylim(deviations.min() - m, deviations.max() + m)\n"
    "    ax.patch.set_facecolor(_BG); ax.set_facecolor(_BG)\n"
    "    ax.grid(color='gray', linestyle='--', linewidth=0.5, alpha=0.2, zorder=0)\n"
    "    for sp in ('bottom', 'left'):\n"
    "        ax.spines[sp].set_color('#ffffff')\n"
    "    for sp in ('top', 'right'):\n"
    "        ax.spines[sp].set_visible(False)\n"
    "    ax.tick_params(colors='#ffffff')\n"
    "    ax.xaxis.label.set_color('#ffffff'); ax.yaxis.label.set_color('#ffffff')\n"
    "    ax.set_xlabel('Pipeline')\n"
    "    ax.set_ylabel(f'{metric} Deviation from MIMIC_Extract Baseline')\n"
    "    ax.set_title(f'Pipeline Impact | {aggregation_method.title()} | {metric}',\n"
    "                 color='#ffffff')\n"
    "    ax.axhline(0, color='white', linewidth=0.8, alpha=0.5)\n"
    "    plt.tight_layout(); plt.show()\n"
    "\n"
    "def visualize_mcnemar_significance(p_values: List[float], names: List[str],\n"
    "                                    title: str = 'McNemar Significance'):\n"
    "    p_values  = [max(float(p) if p == p else 1.0, 1e-20) for p in p_values]\n"
    "    neg_log_p = -np.log10(p_values)\n"
    "    indices   = np.arange(len(names))\n"
    "    colors    = ['#f39c12' if p < 0.05 else '#a0a0a0' for p in p_values]\n"
    "    fig, ax   = plt.subplots(figsize=(10, 6), facecolor=_BG)\n"
    "    ax.set_facecolor(_BG)\n"
    "    bars = ax.bar(indices, neg_log_p, color=colors, alpha=0.85, zorder=3)\n"
    "    ax.axhline(y=-np.log10(0.05), color='#bd3140', linestyle='--',\n"
    "               linewidth=1.5, label='p = 0.05 threshold', zorder=4)\n"
    "    ax.set_xticks(indices)\n"
    "    ax.set_xticklabels(names, rotation=30, ha='right', color='#ffffff')\n"
    "    ax.tick_params(axis='y', colors='#ffffff')\n"
    "    ax.set_ylabel(r'$-\\log_{10}(p)$', color='#ffffff', fontsize=12)\n"
    "    ax.set_xlabel('Aggregation Method', color='#ffffff', fontsize=12)\n"
    "    ax.set_title(title, color='#ffffff', fontsize=14, pad=16)\n"
    "    for bar, p in zip(bars, p_values):\n"
    "        h    = bar.get_height()\n"
    "        disp = f'{p:.3f}' if p > 0.001 else f'{p:.1e}'\n"
    "        ax.text(bar.get_x() + bar.get_width() / 2., h + 0.1, disp,\n"
    "                ha='center', va='bottom', color='#a0a0a0', fontsize=9)\n"
    "    ax.grid(axis='y', color='gray', linestyle='--', linewidth=0.5, alpha=0.2)\n"
    "    for sp in ax.spines.values():\n"
    "        sp.set_color('#444444')\n"
    "    ax.legend(facecolor=_BG, framealpha=0.8, edgecolor='white', labelcolor='white')\n"
    "    plt.tight_layout(); plt.show()\n"
    "\n"
    "def visualize_centroid_shift_v2(shift_tuples: List[Tuple[List[float], List[float]]],\n"
    "                                 titles: List[str], scenario_name: str,\n"
    "                                 vital_names: List[str] = None,\n"
    "                                 epsilon: float = 1e-3, min_range: float = 0.005):\n"
    "    _vnames  = vital_names if vital_names else VITAL_NAMES\n"
    "    hatches  = ['', '//', '..', 'xx', '\\\\\\\\', '++', 'OO', '--']\n"
    "    fig, ax  = plt.subplots(figsize=(20, 8), facecolor=_BG)\n"
    "    n_groups = len(shift_tuples)\n"
    "    indices  = np.arange(len(shift_tuples[0][0]))\n"
    "    bar_w    = 0.8 / n_groups\n"
    "    for g, ((baseline, scores), title_suffix) in enumerate(zip(shift_tuples, titles)):\n"
    "        baseline   = np.array(baseline)\n"
    "        scores     = np.array(scores)\n"
    "        deviations = scores - baseline\n"
    "        pos        = indices + (g - n_groups / 2) * bar_w + bar_w / 2\n"
    "        colors     = ['#3b8465' if d > epsilon else '#bd3140' if d < -epsilon\n"
    "                      else '#a0a0a0' for d in deviations]\n"
    "        ax.bar(pos, deviations, color=colors, width=bar_w,\n"
    "               edgecolor='white', linewidth=0.5, hatch=hatches[g % len(hatches)],\n"
    "               label=title_suffix, zorder=3)\n"
    "        for i, dev in enumerate(deviations):\n"
    "            va     = 'bottom' if dev >= 0 else 'top'\n"
    "            offset = 0.0005 if dev >= 0 else -0.0005\n"
    "            ax.text(pos[i], dev + offset, f'{dev:+.4f}',\n"
    "                    ha='center', va=va, color='#a0a0a0', fontsize=8, fontweight='bold')\n"
    "    ax.set_xticks(indices)\n"
    "    ax.set_xticklabels([v.title() for v in _vnames], rotation=45, ha='right', fontsize=10)\n"
    "    ax.patch.set_facecolor(_BG); ax.set_facecolor(_BG)\n"
    "    ax.grid(color='gray', linestyle='--', linewidth=0.5, alpha=0.2, zorder=0)\n"
    "    for sp in ax.spines.values():\n"
    "        sp.set_color('#ffffff')\n"
    "    ax.tick_params(colors='#ffffff')\n"
    "    ax.xaxis.label.set_color('#ffffff'); ax.yaxis.label.set_color('#ffffff')\n"
    "    ax.set_xlabel('Vital Sign')\n"
    "    ax.set_ylabel('Mean Feature Deviation (EHR − MIMIC_Extract)')\n"
    "    ax.set_title(f'Per-Vital Centroid Shift | {scenario_name}', color='#ffffff')\n"
    "    ax.axhline(0, color='white', linewidth=0.8, alpha=0.5)\n"
    "    ax.legend(facecolor=_BG, labelcolor='white')\n"
    "    plt.tight_layout(); plt.show()"
))

# ── Section 5: Helper Functions ───────────────────────────────────────────────
cells.append(md("## Helper Functions"))
cells.append(code(
    "# ── shared helpers from mimic_extract_analysis ────────────────────────────\n"
    "\n"
    "def _select_pos_label(patients_df, target_label='mortality'):\n"
    "    for col in ('mort_hosp', 'hospital_expire_flag'):\n"
    "        if col in patients_df.columns:\n"
    "            return patients_df[col].astype(int)\n"
    "    raise KeyError('No mortality column found in patients_df')\n"
    "\n"
    "def impute_and_scale(X):\n"
    "    X = X.replace([np.inf, -np.inf], np.nan)\n"
    "    col_means = X.mean(axis=0, skipna=True).fillna(0.0)\n"
    "    X = X.fillna(col_means).fillna(0.0)\n"
    "    scaler = StandardScaler()\n"
    "    return scaler.fit_transform(X.values), scaler, col_means\n"
    "\n"
    "def mcnemar_counts(y_true, pred_a, pred_b):\n"
    "    y   = np.asarray(y_true).astype(int)\n"
    "    a_c = np.asarray(pred_a).astype(int) == y\n"
    "    b_c = np.asarray(pred_b).astype(int) == y\n"
    "    return int(np.sum(~a_c & b_c)), int(np.sum(a_c & ~b_c))\n"
    "\n"
    "def mcnemar_pooled(n01, n10):\n"
    "    n = n01 + n10\n"
    "    if n == 0:\n"
    "        return 0.0, 1.0\n"
    "    stat  = (abs(n01 - n10) - 1.0) ** 2 / n\n"
    "    p_one = binom.cdf(min(n01, n10), n, 0.5)\n"
    "    return float(stat), float(min(1.0, 2.0 * p_one))\n"
    "\n"
    "# ── new helpers for feature alignment ─────────────────────────────────────\n"
    "\n"
    "def aggregate_hourly_matrix(matrix_24x7: pd.DataFrame, method: str) -> pd.Series:\n"
    "    \"\"\"Apply aggregation across 24 hours → 7 feature values.\"\"\"\n"
    "    if method == 'mean':\n"
    "        return matrix_24x7.mean(axis=0, skipna=True)\n"
    "    if method == 'median':\n"
    "        return matrix_24x7.median(axis=0, skipna=True)\n"
    "    if method == 'standard deviation':\n"
    "        return matrix_24x7.std(axis=0, ddof=1, skipna=True)\n"
    "    if method == 'mean deviation':\n"
    "        centered = matrix_24x7 - matrix_24x7.mean(axis=0, skipna=True)\n"
    "        return centered.abs().mean(axis=0, skipna=True)\n"
    "    if method == 'maximum deviation':\n"
    "        centered = matrix_24x7 - matrix_24x7.mean(axis=0, skipna=True)\n"
    "        return centered.abs().max(axis=0, skipna=True)\n"
    "    raise ValueError(f'Unknown method: {method}')\n"
    "\n"
    "def ehr_record_to_hourly_matrix(record, vital_names: List[str]) -> pd.DataFrame:\n"
    "    \"\"\"RecordEHR.timeseries (lists per cell) → 24×7 DataFrame of hourly means.\"\"\"\n"
    "    ts = record.timeseries.copy()\n"
    "    # normalise column names via VITAL_NAME_MAP\n"
    "    ts.columns = [VITAL_NAME_MAP.get(c.lower(), c.lower()) for c in ts.columns]\n"
    "    rows = []\n"
    "    for hour in range(24):\n"
    "        row = {}\n"
    "        for vn in vital_names:\n"
    "            if vn not in ts.columns:\n"
    "                row[vn] = np.nan\n"
    "                continue\n"
    "            cell = ts.iloc[hour][vn] if hour < len(ts) else []\n"
    "            if isinstance(cell, list):\n"
    "                row[vn] = float(np.mean(cell)) if cell else np.nan\n"
    "            elif isinstance(cell, (int, float, np.floating, np.integer)):\n"
    "                row[vn] = float(cell)\n"
    "            else:\n"
    "                row[vn] = np.nan\n"
    "        rows.append(row)\n"
    "    return pd.DataFrame(rows, columns=vital_names)\n"
    "\n"
    "def mimic_record_to_hourly_matrix(X_24h_slice: pd.DataFrame,\n"
    "                                   vital_names: List[str]) -> pd.DataFrame:\n"
    "    \"\"\"vitals_labs slice (all hours, MultiIndex cols) → 24×7 hourly-mean DataFrame.\"\"\"\n"
    "    time_level = None\n"
    "    for name in X_24h_slice.index.names:\n"
    "        if name in ('hours_in', 'time', 'hour'):\n"
    "            time_level = name\n"
    "            break\n"
    "    if time_level is None:\n"
    "        time_level = X_24h_slice.index.names[-1]\n"
    "    hours = X_24h_slice.index.get_level_values(time_level).astype(int)\n"
    "    mean_cols = {str(c[0]).lower(): c\n"
    "                 for c in X_24h_slice.columns\n"
    "                 if isinstance(c, tuple) and str(c[1]).lower() == 'mean'}\n"
    "    rows = []\n"
    "    for h in range(24):\n"
    "        mask = hours == h\n"
    "        row  = {}\n"
    "        for vn in vital_names:\n"
    "            col = mean_cols.get(vn.lower())\n"
    "            if col is None or not mask.any():\n"
    "                row[vn] = np.nan\n"
    "            else:\n"
    "                vals = X_24h_slice.loc[mask, col]\n"
    "                row[vn] = float(vals.mean(skipna=True)) if not vals.isna().all() else np.nan\n"
    "        rows.append(row)\n"
    "    return pd.DataFrame(rows, columns=vital_names)"
))

# ── Section 6: Load & Join Data ───────────────────────────────────────────────
cells.append(md(
    "## Load & Join Data\n\n"
    "`hadm_id` is the join key because it's the only identifier both pipelines\n"
    "carry — MIMIC_Extract is indexed on (subject, hadm, icustay) while the EHR\n"
    "records key on admission alone.\n\n"
    "That mismatch needs resolving: one admission can contain several ICU stays,\n"
    "so MIMIC_Extract has multiple rows where the EHR side has one. We keep the\n"
    "highest `icustay_id`, i.e. the most recent stay. Arbitrary but consistent —\n"
    "and worth remembering that for readmitted patients the two pipelines are\n"
    "then describing different stays.\n\n"
    "`baseline_nofilters` is the MIMIC_Extract scenario used here, since it's the\n"
    "one with no extra cohort filtering applied and so the closest match to what\n"
    "the EHR pipeline produces."
))
cells.append(code(
    "print('Loading MIMIC_Extract patients...')\n"
    "mimic_patients = pd.read_hdf(str(MIMIC_HDF), 'patients')\n"
    "print(f'  {len(mimic_patients):,} patient-stay rows')\n"
    "\n"
    "print('Loading MIMIC_Extract vitals_labs (first-24h slice)...')\n"
    "mimic_X_all = pd.read_hdf(str(MIMIC_HDF), 'vitals_labs')\n"
    "time_level_name = None\n"
    "for _n in mimic_X_all.index.names:\n"
    "    if _n in ('hours_in', 'time', 'hour'):\n"
    "        time_level_name = _n; break\n"
    "if time_level_name is None:\n"
    "    time_level_name = mimic_X_all.index.names[-1]\n"
    "_hour_vals = mimic_X_all.index.get_level_values(time_level_name)\n"
    "mimic_X_24h = mimic_X_all[_hour_vals <= 23]\n"
    "print(f'  vitals_labs 24h rows: {len(mimic_X_24h):,}')\n"
    "\n"
    "print('Loading EHR records...')\n"
    "with open(EHR_PKL, 'rb') as _f:\n"
    "    ehr_records = pickle.load(_f)\n"
    "print(f'  {len(ehr_records):,} EHR records')\n"
    "\n"
    "# ── build hadm_id sets ────────────────────────────────────────────────────\n"
    "mimic_hadm_ids_all = set(mimic_patients.index.get_level_values('hadm_id'))\n"
    "ehr_hadm_ids_all   = {r.admission_id for r in ehr_records}\n"
    "shared_hadm_ids    = mimic_hadm_ids_all & ehr_hadm_ids_all\n"
    "print(f'\\nMIMIC_Extract unique hadm_ids : {len(mimic_hadm_ids_all):,}')\n"
    "print(f'EHR unique hadm_ids           : {len(ehr_hadm_ids_all):,}')\n"
    "print(f'Shared hadm_ids (join cohort) : {len(shared_hadm_ids):,}')\n"
    "\n"
    "# ── deduplicate MIMIC to one icustay_id per hadm_id (keep highest) ────────\n"
    "mimic_idx = mimic_patients.index.to_frame(index=False)\n"
    "mimic_idx = mimic_idx[mimic_idx['hadm_id'].isin(shared_hadm_ids)]\n"
    "mimic_idx = mimic_idx.sort_values('icustay_id').drop_duplicates('hadm_id', keep='last')\n"
    "mimic_idx = mimic_idx.set_index(['subject_id', 'hadm_id', 'icustay_id'])\n"
    "mimic_patients_shared = mimic_patients.loc[mimic_idx.index]\n"
    "\n"
    "# ── filter EHR to shared cohort ───────────────────────────────────────────\n"
    "ehr_records_shared = [r for r in ehr_records if r.admission_id in shared_hadm_ids]\n"
    "# index by hadm_id for fast lookup\n"
    "ehr_by_hadm = {r.admission_id: r for r in ehr_records_shared}\n"
    "\n"
    "# ── build shared ordered list of hadm_ids ─────────────────────────────────\n"
    "shared_hadm_list = sorted(shared_hadm_ids &\n"
    "                           set(mimic_patients_shared.index.get_level_values('hadm_id')) &\n"
    "                           set(ehr_by_hadm.keys()))\n"
    "print(f'\\nFinal aligned cohort: {len(shared_hadm_list):,} records')\n"
    "\n"
    "# ── label vector: hospital mortality from MIMIC_Extract ──────────────────\n"
    "hadm_to_mimic_idx = {\n"
    "    hadm: idx for idx in mimic_patients_shared.index\n"
    "    for hadm in [idx[1]]\n"
    "}\n"
    "mimic_patients_ordered = mimic_patients_shared.loc[\n"
    "    [hadm_to_mimic_idx[h] for h in shared_hadm_list]\n"
    "]\n"
    "y_labels = _select_pos_label(mimic_patients_ordered)\n"
    "print(f'Label prevalence (mort_hosp): {y_labels.mean():.3f}')"
))

# ── Section 7: Feature Extraction ────────────────────────────────────────────
cells.append(md(
    "## Feature Extraction\n\n"
    "Both pipelines get funnelled through the identical two-step path — build a\n"
    "24×7 hourly-mean matrix, then aggregate down the hours to 7 features — even\n"
    "though each already has its own aggregation code.\n\n"
    "That's deliberate. Using each pipeline's own aggregation would mean any\n"
    "difference in the results could be an aggregation difference rather than a\n"
    "preprocessing one, and we'd have no way to tell which. Re-implementing it\n"
    "once here means the only thing that differs between the two feature matrices\n"
    "is what the pipelines did to the data before this point."
))
cells.append(code(
    "# Build per-record MIMIC vitals_labs slice index\n"
    "_mimic_rec_levels = [n for n in mimic_X_24h.index.names if n != time_level_name]\n"
    "_mimic_X_idx      = mimic_X_24h.index.droplevel(time_level_name)\n"
    "\n"
    "def _get_mimic_slice(hadm_id):\n"
    "    \"\"\"Return vitals_labs rows for a single record (all hours ≤ 23).\"\"\"\n"
    "    mimic_row_idx = hadm_to_mimic_idx[hadm_id]\n"
    "    mask = _mimic_X_idx.isin([mimic_row_idx])\n"
    "    return mimic_X_24h[mask]\n"
    "\n"
    "FEATURE_MATRICES = {}  # method → {'mimic': DataFrame, 'ehr': DataFrame}\n"
    "\n"
    "for method in AGG_METHODS:\n"
    "    print(f'Extracting features: {method} ...')\n"
    "    mimic_rows, ehr_rows = [], []\n"
    "    for hadm_id in shared_hadm_list:\n"
    "        # MIMIC_Extract\n"
    "        slice_m = _get_mimic_slice(hadm_id)\n"
    "        mat_m   = mimic_record_to_hourly_matrix(slice_m, VITAL_NAMES)\n"
    "        feat_m  = aggregate_hourly_matrix(mat_m, method)\n"
    "        mimic_rows.append(feat_m.values)\n"
    "        # EHR\n"
    "        rec_e  = ehr_by_hadm[hadm_id]\n"
    "        mat_e  = ehr_record_to_hourly_matrix(rec_e, VITAL_NAMES)\n"
    "        feat_e = aggregate_hourly_matrix(mat_e, method)\n"
    "        ehr_rows.append(feat_e.values)\n"
    "    X_mimic = pd.DataFrame(mimic_rows, index=shared_hadm_list, columns=VITAL_NAMES)\n"
    "    X_ehr   = pd.DataFrame(ehr_rows,   index=shared_hadm_list, columns=VITAL_NAMES)\n"
    "    FEATURE_MATRICES[method] = {'mimic': X_mimic, 'ehr': X_ehr}\n"
    "    print(f'  MIMIC NaN%: {X_mimic.isna().mean().mean():.3f}   '\n"
    "          f'EHR NaN%: {X_ehr.isna().mean().mean():.3f}')\n"
    "\n"
    "print('\\nFeature extraction complete.')"
))

# ── Section 8: Cohort & Data Quality Summary ──────────────────────────────────
cells.append(md(
    "## Cohort & Data Quality Summary\n\n"
    "Per-pipeline per-vital missingness and label prevalence on the shared cohort."
))
cells.append(code(
    "method0 = AGG_METHODS[0]\n"
    "X_m0 = FEATURE_MATRICES[method0]['mimic']\n"
    "X_e0 = FEATURE_MATRICES[method0]['ehr']\n"
    "\n"
    "quality_rows = []\n"
    "for vn in VITAL_NAMES:\n"
    "    miss_m = X_m0[vn].isna().mean() * 100\n"
    "    miss_e = X_e0[vn].isna().mean() * 100\n"
    "    quality_rows.append({\n"
    "        'Vital': vn.title(),\n"
    "        'MIMIC_Extract missing%': f'{miss_m:.1f}',\n"
    "        'EHR missing%':           f'{miss_e:.1f}',\n"
    "    })\n"
    "\n"
    "print(tabulate(quality_rows, headers='keys', tablefmt='github'))\n"
    "print(f'\\nCohort size           : {len(shared_hadm_list):,}')\n"
    "print(f'Label prevalence      : {y_labels.mean():.3f} (hospital mortality)')\n"
    "print(f'Positive cases        : {int(y_labels.sum()):,}')\n"
    "print(f'Negative cases        : {int((y_labels == 0).sum()):,}')"
))

# ── Section 9: Matched Classifier Evaluation ─────────────────────────────────
cells.append(md(
    "## Matched Classifier Evaluation\n\n"
    "Logistic regression rather than anything stronger, on purpose: a simple model\n"
    "is more sensitive to feature quality, which is exactly what's being measured.\n"
    "A random forest would paper over preprocessing differences.\n\n"
    "The split indices are computed once per seed and reused for both pipelines,\n"
    "so each pair of models sees the same patients in train and test. Stratified,\n"
    "because mortality prevalence is low enough that an unstratified split can\n"
    "leave a test set with very few positives.\n\n"
    "Read AUC-ROC over accuracy here — with this class imbalance, predicting\n"
    "\"survives\" for everyone already scores well."
))
cells.append(code(
    "y_arr = y_labels.values.astype(int)\n"
    "\n"
    "EVAL_RESULTS = {}  # method → {'mimic': {...}, 'ehr': {...}}\n"
    "\n"
    "for method in AGG_METHODS:\n"
    "    X_mimic = FEATURE_MATRICES[method]['mimic']\n"
    "    X_ehr   = FEATURE_MATRICES[method]['ehr']\n"
    "\n"
    "    res_m = dict(acc=[], f1=[], auc=[], preds=[], y_test_list=[])\n"
    "    res_e = dict(acc=[], f1=[], auc=[], preds=[], y_test_list=[])\n"
    "\n"
    "    for seed in SEEDS:\n"
    "        sss = StratifiedShuffleSplit(n_splits=1, test_size=TEST_SIZE, random_state=seed)\n"
    "        train_idx, test_idx = next(sss.split(X_mimic, y_arr))\n"
    "\n"
    "        for res, X_raw in [(res_m, X_mimic), (res_e, X_ehr)]:\n"
    "            X_sc, _, _ = impute_and_scale(X_raw)\n"
    "            Xtr, Xte   = X_sc[train_idx], X_sc[test_idx]\n"
    "            ytr, yte   = y_arr[train_idx], y_arr[test_idx]\n"
    "            clf = LogisticRegression(**MODEL_KWARGS)\n"
    "            clf.fit(Xtr, ytr)\n"
    "            pred   = clf.predict(Xte)\n"
    "            prob   = clf.predict_proba(Xte)[:, 1]\n"
    "            res['acc'].append(accuracy_score(yte, pred))\n"
    "            res['f1'].append(f1_score(yte, pred, average='weighted', zero_division=0))\n"
    "            res['auc'].append(roc_auc_score(yte, prob) if len(np.unique(yte)) > 1 else np.nan)\n"
    "            res['preds'].append(pred)\n"
    "            res['y_test_list'].append(yte)\n"
    "\n"
    "    EVAL_RESULTS[method] = {'mimic': res_m, 'ehr': res_e}\n"
    "\n"
    "# ── print summary table ───────────────────────────────────────────────────\n"
    "table_rows = []\n"
    "for method in AGG_METHODS:\n"
    "    for pipeline_key, label in [('mimic', 'MIMIC_Extract'), ('ehr', 'EHR')]:\n"
    "        res = EVAL_RESULTS[method][pipeline_key]\n"
    "        table_rows.append({\n"
    "            'Method':   method,\n"
    "            'Pipeline': label,\n"
    "            'Accuracy': f\"{np.mean(res['acc']):.4f} ± {np.std(res['acc']):.4f}\",\n"
    "            'F1':       f\"{np.mean(res['f1']):.4f} ± {np.std(res['f1']):.4f}\",\n"
    "            'AUC-ROC':  f\"{np.nanmean(res['auc']):.4f} ± {np.nanstd(res['auc']):.4f}\",\n"
    "        })\n"
    "\n"
    "print(tabulate(table_rows, headers='keys', tablefmt='github'))"
))

# ── Section 10: Pipeline Impact Visualization ─────────────────────────────────
cells.append(md(
    "## Pipeline Impact Visualization\n\n"
    "Aurora bar charts showing EHR-Dataset-Processing accuracy / F1 deviation\n"
    "from the MIMIC_Extract baseline, per aggregation method."
))
cells.append(code(
    "for method in AGG_METHODS:\n"
    "    mimic_res = EVAL_RESULTS[method]['mimic']\n"
    "    ehr_res   = EVAL_RESULTS[method]['ehr']\n"
    "    for metric, key in [('Accuracy', 'acc'), ('F1', 'f1'), ('AUC-ROC', 'auc')]:\n"
    "        mimic_score = float(np.mean(mimic_res[key]))\n"
    "        ehr_score   = float(np.nanmean(ehr_res[key]))\n"
    "        visualize_pipeline_impact(\n"
    "            scores         = [mimic_score, ehr_score],\n"
    "            pipeline_names = ['EHR-Dataset-Processing'],\n"
    "            metric         = metric,\n"
    "            aggregation_method = method,\n"
    "        )"
))

# ── Section 11: McNemar's Test ────────────────────────────────────────────────
cells.append(md(
    "## McNemar's Test\n\n"
    "Whether one pipeline scores half a point higher than the other is not very\n"
    "interesting on its own — at this sample size that's comfortably inside seed\n"
    "noise. McNemar asks the sharper question: on the patients where the two\n"
    "models disagree, is the disagreement lopsided enough to be real?\n\n"
    "Discordant counts are pooled across all four seeds rather than testing each\n"
    "separately, which avoids both the multiple-comparisons problem and the\n"
    "temptation to report whichever seed gave the nicest p-value.\n\n"
    "Note this compares the models against each other, not against ground truth —\n"
    "it says they differ, not which is right. Read it next to the accuracy table."
))
cells.append(code(
    "mcnemar_p_values = []\n"
    "\n"
    "for method in AGG_METHODS:\n"
    "    mimic_res = EVAL_RESULTS[method]['mimic']\n"
    "    ehr_res   = EVAL_RESULTS[method]['ehr']\n"
    "    total_n01, total_n10 = 0, 0\n"
    "    for seed_idx in range(len(SEEDS)):\n"
    "        yte    = mimic_res['y_test_list'][seed_idx]\n"
    "        pred_m = mimic_res['preds'][seed_idx]\n"
    "        pred_e = ehr_res['preds'][seed_idx]\n"
    "        n01, n10 = mcnemar_counts(yte, pred_m, pred_e)\n"
    "        total_n01 += n01\n"
    "        total_n10 += n10\n"
    "    _, p = mcnemar_pooled(total_n01, total_n10)\n"
    "    mcnemar_p_values.append(p)\n"
    "    print(f'{method:<25} n01={total_n01:4d}  n10={total_n10:4d}  p={p:.4f}')\n"
    "\n"
    "visualize_mcnemar_significance(\n"
    "    p_values = mcnemar_p_values,\n"
    "    names    = AGG_METHODS,\n"
    "    title    = 'McNemar\\'s Test: MIMIC_Extract vs EHR-Dataset-Processing',\n"
    ")"
))

# ── Section 12: Per-Vital Feature Distribution ───────────────────────────────
cells.append(md(
    "## Per-Vital Feature Distribution Comparison\n\n"
    "Same patients, same vitals, same window — so in principle both pipelines\n"
    "should report the same mean heart rate. Where they don't, the gap is a direct\n"
    "measurement of what their preprocessing did differently, and it's often more\n"
    "informative than the accuracy numbers.\n\n"
    "A large gap on one vital usually points at something specific: different\n"
    "outlier bounds, a unit conversion, or a different set of item IDs feeding it."
))
cells.append(code(
    "for method in AGG_METHODS:\n"
    "    X_mimic = FEATURE_MATRICES[method]['mimic']\n"
    "    X_ehr   = FEATURE_MATRICES[method]['ehr']\n"
    "\n"
    "    def _imputed_means(X):\n"
    "        X2 = X.replace([np.inf, -np.inf], np.nan)\n"
    "        col_means = X2.mean(skipna=True).fillna(0.0)\n"
    "        X2 = X2.fillna(col_means)\n"
    "        return X2.mean(axis=0).values\n"
    "\n"
    "    centroid_m = _imputed_means(X_mimic)\n"
    "    centroid_e = _imputed_means(X_ehr)\n"
    "\n"
    "    print(f'\\n=== {method} ===')\n"
    "    for vn, vm, ve in zip(VITAL_NAMES, centroid_m, centroid_e):\n"
    "        print(f'  {vn:<35} MIMIC={vm:8.3f}  EHR={ve:8.3f}  Δ={ve-vm:+.3f}')\n"
    "\n"
    "    visualize_centroid_shift_v2(\n"
    "        shift_tuples  = [([centroid_m[i] for i in range(len(VITAL_NAMES))],\n"
    "                          [centroid_e[i] for i in range(len(VITAL_NAMES))])],\n"
    "        titles        = ['EHR vs MIMIC_Extract'],\n"
    "        scenario_name = method.title(),\n"
    "        vital_names   = VITAL_NAMES,\n"
    "    )"
))

# ── Section 13: Summary Dashboard ────────────────────────────────────────────
cells.append(md(
    "## Summary Dashboard\n\n"
    "Consolidated bar chart: MIMIC_Extract vs EHR-Dataset-Processing across\n"
    "all 5 aggregation methods for Accuracy and F1."
))
cells.append(code(
    "fig, axes = plt.subplots(1, 2, figsize=(18, 7), facecolor=_BG)\n"
    "bar_w = 0.35\n"
    "indices = np.arange(len(AGG_METHODS))\n"
    "grad = generate_hex_gradient(_AURORA, 6)\n"
    "colors_m = grad[2]  # mid-purple for MIMIC\n"
    "colors_e = grad[4]  # teal/green for EHR\n"
    "\n"
    "for ax_idx, (metric_key, metric_label) in enumerate([('acc', 'Accuracy'), ('f1', 'F1')]):\n"
    "    ax = axes[ax_idx]\n"
    "    ax.set_facecolor(_BG)\n"
    "    mimic_scores = [np.mean(EVAL_RESULTS[m]['mimic'][metric_key]) for m in AGG_METHODS]\n"
    "    ehr_scores   = [np.nanmean(EVAL_RESULTS[m]['ehr'][metric_key])   for m in AGG_METHODS]\n"
    "    mimic_stds   = [np.std(EVAL_RESULTS[m]['mimic'][metric_key])   for m in AGG_METHODS]\n"
    "    ehr_stds     = [np.nanstd(EVAL_RESULTS[m]['ehr'][metric_key])    for m in AGG_METHODS]\n"
    "\n"
    "    b1 = ax.bar(indices - bar_w/2, mimic_scores, bar_w,\n"
    "                label='MIMIC_Extract', color=colors_m, yerr=mimic_stds,\n"
    "                error_kw=dict(ecolor='white', capsize=4), zorder=3)\n"
    "    b2 = ax.bar(indices + bar_w/2, ehr_scores, bar_w,\n"
    "                label='EHR-Dataset-Processing', color=colors_e, yerr=ehr_stds,\n"
    "                error_kw=dict(ecolor='white', capsize=4), zorder=3)\n"
    "\n"
    "    ax.set_xticks(indices)\n"
    "    ax.set_xticklabels([m.title() for m in AGG_METHODS], rotation=30, ha='right')\n"
    "    ax.set_ylabel(metric_label, color='white')\n"
    "    ax.set_title(f'{metric_label} by Aggregation Method', color='white')\n"
    "    ax.grid(axis='y', color='gray', linestyle='--', linewidth=0.5, alpha=0.3)\n"
    "    for sp in ax.spines.values():\n"
    "        sp.set_color('#444444')\n"
    "    ax.legend(facecolor=_BG, labelcolor='white')\n"
    "\n"
    "fig.suptitle('Pipeline Comparison — MIMIC_Extract vs EHR-Dataset-Processing\\n'\n"
    "             'Hospital Mortality | Logistic Regression | 4-seed Stratified Split',\n"
    "             color='white', fontsize=14, y=1.01)\n"
    "plt.tight_layout()\n"
    "plt.show()"
))

# ── Assemble notebook ─────────────────────────────────────────────────────────
notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11.0"},
    },
    "cells": cells,
}

out_path = Path(__file__).parent / 'pipeline_comparison.ipynb'
with open(out_path, 'w') as f:
    json.dump(notebook, f, indent=1)

print(f'Written: {out_path}  ({out_path.stat().st_size:,} bytes, {len(cells)} cells)')
